server:
  port: 8001

spring:
  application:
    name: Weather-Cloud-Provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weather
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: Weather-Cloud-Provider-8001
    prefer-ip-address: true

info:
  app.name: ${project.version}
